#! /bin/bash

# Define variables of the build

# where things come from
ups_url=http://oink.fnal.gov/distro/relocatable-ups/ups-upd-4.9.7-source.tar.bz2
art_ext_url=http://oink.fnal.gov/distro/art/art_externals-0.06.03-source.tar.bz2
art_suite_url=http://oink.fnal.gov/distro/art/art_suite-1.03.08-source.tar.bz2
nu_ext_url=http://oink.fnal.gov/distro/art/nu_extras-0.06.03-source.tar.bz2

# where things go
downloads=$top/downloads
products=$top/products
patchdir=$top/patches
logdir=$top/logs


